### PR TITLE
remove sleep from pbar update loop

### PR DESCRIPTION
**Pull request by mkolopanis**
remove sleep introduced in last PR. Turns out it serializes the execution of the task loop, 
Ran reference sim 1.1 before and after this change and the before is very slow, but after completes in ~.03 minutes same as before last PR

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

For all pull requests:
- [x] I have read the [contribution guide](CONTRIBUTING.md).
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by mkolopanis** [comment]
@bhazelton I think this will require admin to merge because I've removed covered lines, but I don't think it is reasonable to serialize a uvtask to once a second.

**Comment by bhazelton** [comment]
I don't think you do -- the test that's failing is not a required tea for exactly this reason.

**Comment by mkolopanis** [comment]
Oh okay thanks! Always get scared at red x

**Review by aelanman — APPROVED** [review]
Thanks for spotting this!

**Pull request merged**
