### PR TITLE
perf: allow not running checks

### PR DESCRIPTION
**Pull request by steven-murray**
## Description

Since `UVData.new()` already runs an object check, we pass the `check_kw` to it instead of running the object check in `_complete_data`. The object check actually takes a somewhat significant amount of time (because it has to recompute all the LSTs to check them...) so it's good to give the user control over when it should be run, and remove duplication.

## Motivation and Context

HERA validation sims.

## Types of changes

- [x] Performance enhancement
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

For all pull requests:
- [x] I have read the [contribution guide](CONTRIBUTING.md).
- [x] My code follows the code style of this project.

### CODE REVIEW

**Comment by bhazelton** [comment]
Does this require some of the recent changes to pyuvdata?

**Comment by steven-murray** [comment]
@bhazelton yes it requires the `check_kw` parameter to `UVData.new()` which came in 3.1.2.

**Comment by steven-murray** [comment]
Are we OK requiring >=3.1.2, or do you want me to do a version check in the code?

**Review by bhazelton — COMMENTED** [review]
need to also update `environment.yml` and the readme with these new versions.

**Review by bhazelton — APPROVED** [review]
Looks good.

**Pull request merged**
