### PR TITLE
Add a workflow to run hera_sim tests

### PR DESCRIPTION
**Pull request by bhazelton**
## Description

Add a github actions workflow to run hera_sim tests.

## Motivation and Context

Help with awareness of the effect of changes on hera_sim.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [x] Build or continuous integration change

## Checklist:

Build or continuous integration change checklist:
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the readme to reflect this.
- [ ] If this is a new CI setup, I have added the associated badge to the readme and to references/make_index.py (if appropriate).

### CODE REVIEW

**Comment by bhazelton** [comment]
@aelanman It looks like this is largely working, but is erroring on a test that calls `healvis` in a way that looks related to these changes.

**Comment by steven-murray** [comment]
@bhazelton the error you're getting there should be fixed when https://github.com/HERA-Team/hera_sim/pull/106 is merged to master.

**Comment by bhazelton** [comment]
@steven-murray we could change it, but the utility of these kinds of tests (which we have on pyuvdata and pyradiosky) is to help us know when we've broken things downstream. Most of the time if we're careful we can know when we're making breaking changes that need some deprecation, but occasionally there's a surprise -- some subtle effect that we didn't anticipate. In that case, testing when we push to master is a bit late. Of course this can be managed by making release candidates and having other repos test against them, but this mechanism has been pretty effective for us on other repositories.

**Comment by steven-murray** [comment]
@bhazelton sure thing -- certainly safer this way, if you're happy with the
little bit of extra testing time!

**Comment by bhazelton** [comment]
@steven-murray @aelanman I thought these tests should pass now, but I'm still getting this error:
`TypeError: initialize_catalog_from_params() got an unexpected keyword argument 'return_recarray'`

**Comment by aelanman** [comment]
Is hera_sim installing pyuvsim from PyPi? The return_recarray option was added with the skymodel_sharedmem PR, which may not have been released.

**Comment by bhazelton** [comment]
No, it's installing from the repo so that we can test changes to this repo.

**Comment by bhazelton** [comment]
ok this is passing now. @steven-murray can you re-review?

**Pull request merged**
