### PR TITLE
Docs cleanup

### PR DESCRIPTION
**Pull request by dseitova**
Changed docs folder

## Description
 Created reference_simulation_memos folder, added memos there; created Images folder, moved png files to that folder and updated the path for files that used those images

## Motivation and Context
 Just cleaned up the docs folder

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [x] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

Bug fix checklist:
- [ ] My fix includes a new test that breaks as a result of the bug (if possible).
- [ ] All new and existing tests pass in both python 2 and python 3.
- [ ] I have checked that I reproduce the reference simulations or if there are differences they are explained below (if appropriate). If there are changes that are correct, I will update the reference simulation files after this PR is merged.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md).

New feature checklist:
- [ ] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the documentation to highlight my new feature (if appropriate).
- [ ] I have added tests to cover my new feature.
- [ ] All new and existing tests pass in both python 2 and python 3.
- [ ] I have checked that I reproduce the reference simulations or if there are differences they are explained below (if appropriate). If there are changes that are correct, I will update the reference simulation files after this PR is merged.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md).

Breaking change checklist:  
- [ ] I have updated the docstrings associated with my change using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the documentation to reflect my changes (if appropriate).
- [ ] My change includes backwards compatibility and deprecation warnings (if possible).
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass in both python 2 and python 3.
- [ ] I have checked that I reproduce the reference simulations or if there are differences they are explained below (if appropriate). If there are changes that are correct, I will update the reference simulation files after this PR is merged.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md).

Reference simulation update or replacement:
- [ ] If this is a new reference simulation or if the settings files have changed, I have added all the relevant files to the reference_simulations folder.
- [ ] If this is a new reference simulation I have fully documented it in a memo in docs and updated any other docs as appropriate.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md).

Documentation change checklist:
- [ ] Any updated docstrings use the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] If this is a significant change to the readme or other docs, I have checked that they are rendered properly on ReadTheDocs. (you may need help to get this branch to build on RTD, just ask!)

Version change checklist:
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md) to put all the unreleased changes under the new version (leaving the unreleased section empty).
- [ ] I have run the appropriate tests for this level of version change (described in the readme under versioning).

Build or continuous integration change checklist:
- [ ] If required or optional dependencies have changed (including version numbers), I have updated the readme to reflect this.
- [ ] If this is a new CI setup, I have added the associated badge to the readme and to references/make_index.py (if appropriate).

### CODE REVIEW

**Comment by dseitova** [comment]
@aelanman suggested yesterday that memos should be in the docs folder, as he plans to change/get rid of reference simulations folder in the future but I can move them for now if you want?

**Comment by aelanman** [comment]
I can see the advantage of keeping the `reference_simulations` directory and putting the memos there. I figured that memos (whether or not about reference sims) should go in `docs`, but if reference simulation is going to be a critical part of development then it deserves it own directory.

**Comment by jpober** [comment]
Yeah, I was sort of viewing reference simulations as a major scientific component of the project, whereas docs described things more like readmes, tutorials, etc.  So if you don't object, let's try something like what I suggested and see how it looks?

**Comment by aelanman** [comment]
That makes sense. It sounds like the main task then is cleaning up the `reference_simulations` folder, not the `docs`.

@dseitova Do you want to do what Jonathan suggested, or should I?

**Comment by dseitova** [comment]
I can do it!

**Comment by jpober** [comment]
I think that looks good.  Let's put the stuff from docs/references in the reference_simulations folder too and I think it'll be good to go!

**Comment by jpober** [comment]
Thanks!  Maybe rename the references folder in reference_simulations to Description or something else that better indicates that the overview memo is in there.  Then I think it will be all set!

**Comment by jpober** [comment]
Looks great!

**Pull request merged**
