### PR TITLE
Parallel test bug resolution

### LINKED ISSUE #341: Bug with parallelized tests which fail in serial mode
MPI-enabled tests work by spawning a subprocess to run pytest with `mpirun`. The pytest hook `pytest_runtest_call` identifies if a given test has the `parallel` marker and spawns the subprocess. However, if the subprocess finishes without error (that is, the test passes), the main thread then goes on to run the test (without parallelization, in serial mode). If you have a test that will only pass with multiple MPI processes, it will fail at this step. This hasn't come up before because all of our tests have passed in serial mode if they pass in parallel.

There's a fairly simple fix to this -- If the subprocess completes (i.e., the parallelized test passes), replace the test function in the main thread with a blank function that doesn't do anything. This has been implemented here:
https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/4724f417999025a4080d753549a28cd7c08caac8/pyuvsim/tests/conftest.py#L113-L116

### PR DESCRIPTION
**Pull request by aelanman**
## Description

Generalizes parallel tests to run with different "root" processes. Writing this uncovered a bug in parallel pytest, which is also resolved here.
Also adds a `ParallelFlag` class which isn't used, but might be useful. This provides a set of flags across all MPI processes which can be checked asynchronously by the root process.

## Motivation and Context

Currently, parallelized tests which pass with Npus > 1 but fail with Npus == 1 will fail in general with pytest due to this bug. Ideally, the `parallel` marker means that a given test should be pass with the specified Npus, and whether or not it passes with Npus==1 is irrelevant.

Fixes #341 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [ ] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

For all pull requests:
- [ ] I have read the [contribution guide](CONTRIBUTING.md).
- [ ] My code follows the code style of this project.

Bug fix checklist:
- [x] My fix includes a new test that breaks as a result of the bug (if possible).
- [x] All new and existing tests pass.
- [ ] I have checked that I reproduce the reference simulations or if there are differences they are explained below (if appropriate). If there are changes that are correct, I will update the reference simulation files after this PR is merged.
- [ ] I have checked (e.g., using the benchmarking tools) that this change does not significantly increase typical runtimes. If it does, I have included a justification in the comments on this PR.
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md).

New feature checklist:
- [ ] I have added or updated the docstrings associated with my feature using the [numpy docstring format](https://numpydoc.readthedocs.io/en/latest/format.html).
- [ ] I have updated the documentation to highlight my new feature (if appropriate).
- [ ] I have added tests to cover my new feature.
- [ ] All new and existing tests pass.
- [ ] I have checked that I reproduce the reference simulations or if there are differences they are explained below (if appropriate). If there are changes that are correct, I will update the reference simulation files after this PR is merged.
- [ ] I have checked (e.g., using the benchmarking tools) that this change does not significantly increase typical runtimes. If it does, I have included a justification in the comments on this PR.
- [ ] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/master/CHANGELOG.md).

### CODE REVIEW

**Review by bhazelton — DISMISSED** [review]
This looks fine to me, but I'm really not an MPI expert. I'll approve for now, but won't merge yet until @mkolopanis can weigh in if he wants to.

**Review by mkolopanis — COMMENTED** [review]
Thanks for finding and fixing that test execution bug. I suppose my only real comment is why add this ParallelFlag class if we're not using it for anything? Feels like extra code we're just carrying around at that point. I agree it could be potentially useful but its implementation is not terribly complex either and I think we could easily re-create it if we find a need.

**Comment by aelanman** [comment]
@mkolopanis I just didn't want to delete it after writing it, but it doesn't need to be there. I'll remove it.

**Comment by mkolopanis** [comment]
I totally understand that. Never fun to write something, then throw it away.

**Review by mkolopanis — APPROVED** [review]
Looks good to me! Thanks @aelanman

**Pull request merged**
