### PR TITLE
Prepare for v1.3

### PR DESCRIPTION
**Pull request by bhazelton**
Update the changelog for the new version.

Also fix incorrect old release dates and handle an intermittent error in tests.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [ ] Documentation change (documentation changes only)
- [x] Version change
- [ ] Build or continuous integration change

## Checklist:

For all pull requests:
- [x] I have read the [contribution guide](CONTRIBUTING.md).
- [x] My code follows the code style of this project.

Version change checklist:
- [x] I have updated the [CHANGELOG](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/main/CHANGELOG.md) to put all the unreleased changes under the new version (leaving the unreleased section empty).
- [ ] I have run the appropriate tests for this level of version change (described in the readme under versioning).

### CODE REVIEW

**Comment by bhazelton** [comment]
Yeah, it's flaky. I don't understand why, it may be a downloading thing but the error is not clearly caused by that. @aelanman may have more info. We've done some of this kind of handling for these error and JPL errors on pyuvdata.

**Comment by aelanman** [comment]
There's some intermittent error in how lunarsky defines and clears topocentric frames. I've managed to reproduce it, but haven't made much progress in fixing it. It _should_ only be an issue in rare cases when you're generating and deleting lots of `LunarTopo` instances, so I think it's fine for this release. If we're really worried, maybe we can add a warning about flakiness?

**Comment by jpober** [comment]
Worried is a strong word, but it might be nice if there's a way to warn that this test was skipped.  If that isn't feasible, I'll go ahead and approve and merge.

**Comment by bhazelton** [comment]
I don't know of a way to surface that up to a comment on the PR other than letting the test fail. But you can look at the CI logs in detail to see if tests were skipped. I agree it's not ideal to skip them but my experience is that usually at most 2 of the CI runs have this problem and it usually goes away if I re-run them.

**Review by jpober — APPROVED** [review]
Ok, sounds good.  I'm approving.

**Pull request merged**
