### PR TITLE
Description of comparisons. Better than nothing.

### LINKED ISSUE #167: summary of first reference sim validation
This memo will summarize the first reference simulation, what questions were we hoping to answer, what parameters did we choose and why, what did we learn from comparison with prisim outputs, and most importantly summarize the precision attained. The goal is to be able to quote a single number for how closely prisim and pyuvsim agree.

### PR DESCRIPTION
**Pull request by dannyjacobs**
## Description
A basic Readme for the comparisons directory. It could be better.

## Motivation and Context
Explains why the reference simulations exist and gives some basic information about how to reproduce them.
closes #167 
## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Reference simulation update or replacement
- [x] Documentation change (documentation changes only)
- [ ] Version change
- [ ] Build or continuous integration change

## Checklist:

No checklists are relevant.

### CODE REVIEW

**Comment by bhazelton** [comment]
@dannyjacobs you need to rebase this branch to get tests to pass.

**Comment by aelanman** [comment]
Instead of reviewing this, would it be okay if I made some edits directly?

**Comment by jpober** [comment]
@aelanman sounds great, then I’ll re-review

**Comment by aelanman** [comment]
This still need to be rebased. I've made some changes to the memo cleaning up a table, rewording, and making sectioning clearer with markdown syntax.

**Comment by jpober** [comment]
@aelanman Was this rebased off the beamlist branch?  I see references to beamdicts now.  If so, maybe I should wait to review until that's merged?

That said, the memo looks pretty good.  Viewing it through github, the table formatting is awkward -- the last column is too narrow, making the table very tall, to the point where I can't see the left/right scroll bar at the bottom while reading the table.  I also see a spot in the memo where there's a note to add an image.

@dannyjacobs @aelanman Let me know how you'd like me to proceed with the review.

**Comment by aelanman** [comment]
I think this was rebased off a version of master that didn't include the `profiling_updates` merge. I'll try to fix it now.

**Comment by jpober** [comment]
Ok, that looks better.  I still find the table awkward but I'm to merge if you're done working on it.

**Comment by dannyjacobs** [comment]
Let me make a suggestion.

**Comment by dannyjacobs** [comment]
Move the test description/rationale into a separate table?  The details are only important once you pick which reference test you want to do. Would look like this:
image

**Comment by aelanman** [comment]
Agreed, that looks much better.

**Comment by jpober** [comment]
Yes, I think that would help a lot too.

**Comment by bhazelton** [comment]
Tests should pass if you rebase this.

**Pull request merged**
